# Generated by Django 4.2.10 on 2024-06-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orders_created_at_alter_ordersitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
