# Generated by Django 4.2.10 on 2024-06-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_product_quantity'),
        ('order', '0003_alter_ordersitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.product'),
        ),
    ]
