# Generated by Django 4.2.8 on 2024-06-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordersitem',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordersitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
