# Generated by Django 4.2.10 on 2024-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('car_name', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speed', models.CharField(max_length=50)),
                ('gps', models.CharField(max_length=100)),
                ('seat_type', models.CharField(max_length=100)),
                ('automatic', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
