# Generated by Django 4.2.10 on 2024-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='car_name',
            new_name='carName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img_url',
            new_name='imgUrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seat_type',
            new_name='seatType',
        ),
    ]
